### ISSUE TITLE
Major Module: Set up the backend using Django framework.

### ISSUE THREAD

**Issue by abaiao-r** [abaiao-r/ft_transcendence#2]
Major module: Use a Framework as backend.

In this major module, you are required to utilize a specific web framework for our backend development, and that framework is Django.

You can create a backend without using the constraints of this module
by using the default language/framework. However, this module will
only be valid if you use the associated constraints.

**Comment by IcQuackson** [comment]
yap. done. now i just do maintaining and implement new features as we need
