### ISSUE TITLE
Tournament Options UI Revamp

### ISSUE THREAD

**Issue by IcQuackson** [abaiao-r/ft_transcendence#65]
**Problem:**
The current Tournament Options UI may be confusing to users:
1. Users must identify the host with a checkbox.
2. Errors arise from combinations with the isAI checkbox.
3. Errors appear only after clicking "Start Tournament," creating a barrier.

**Proposed Solution:**
1. Visibly lock a player card for the host (no need to use the term "host," just indicate the host player).
2. Keep allowing the host to change the display name.
3. Replace the isAI checkbox with a more user-friendly option (I suggest the **Segment Control** component like the picture).
![image](https://github.com/abaiao-r/ft_transcendence/assets/61185097/86897a8d-1563-46ec-83fe-9df42bc07752)

Implementing these changes will turn tournament options error handling **obsolete**.

**Comment by abaiao-r** [comment]
Done.
