### ISSUE TITLE
Improve Match History Card Styling and Interactivity

### ISSUE THREAD

**Issue by IcQuackson** [abaiao-r/ft_transcendence#69]
- **Current Issue:** 
  - Clicking on a match card in the match history reveals only 2 stats without any styling.
  - Clicking on multiple match cards in the same row causes them to resize to fit the content, which is just 2 paragraphs.
  - No visual cues indicate that the cards are clickable.

- **Task:** 
  - Add styling to the back of the match cards.
  - Fix resizing bugs to maintain consistent card size.
  - Implement visual cues to indicate clickability.

**Comment by abaiao-r** [comment]
Any idea for this @IcQuackson : Implement visual cues to indicate clickability.

**Comment by abaiao-r** [comment]
size done

**Comment by abaiao-r** [comment]
visiblity made
