### ISSUE TITLE
Major Module: Implementing a remote authentication OAuth 2.0 authentication with 42.

### ISSUE THREAD

**Issue by abaiao-r** [abaiao-r/ft_transcendence#7]
Key features and objectives include:

Be carefull, the management of duplicate usernames/emails is at your
discretion. You must provide a justification for your decision.

◦ Integrate the authentication system, allowing users to securely sign in.
◦ Obtain the necessary credentials and permissions from the authority to enable
a secure login.
◦ Implement user-friendly login and authorization flows that adhere to best practices and security standards.
◦ Ensure the secure exchange of authentication tokens and user information between the web application and the authentication provider.

This major module aims to get a remote user authentication, providing users with a secure and convenient way to access the web application.

**Comment by IcQuackson** [comment]
@joao-per already did this
